config/routes.rb
Rails.application.routes.draw do
  root to: "hairstyle_lists#show", id: 1
  resources :hairstyle_lists, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hairstyle.rb
class Hairstyle
  include Attrio

  define_attributes do
    attr :colour, String
    attr :part, String
    attr :style, String
    attr :length, String
    attr :id, String
  end

  def initialize(params = {})
    self.attributes = params
  end

  def attributes=(attributes = {})
    attributes.each do |attr, value|
      send("#{attr}=", value) if respond_to?("#{attr}=")
    end
  end
end

app/models/hairstyle_list.rb
class HairstyleList < ApplicationRecord
  attribute :style_attributes, OrderedJSONB::Type.new

  def styles
    hairstyle_styles.styles
  end

  def styles=(styles_attrs)
    return unless styles_attrs
    self.style_attributes_will_change!
    self.style_attributes = styles_attrs
    hairstyle_styles.styles = styles_attrs
  end

  def find_style(id)
    styles.find { |style| style.id == id }
  end

  private

  def hairstyle_styles
    @styles ||= Hairstyles.new(style_attributes)
  end
end

app/models/hairstyles.rb
class Hairstyles
  def initialize(hairstyles_attrs)
    @hairstyles_attrs = hairstyles_attrs
  end

  def styles
    @styles ||= @hairstyles_attrs.map do |id, style_params|
      style_params[:id] = id
      Hairstyle.new(style_params.with_indifferent_access)
    end
  end

  def styles=(styles_attrs)
    @styles = styles_attrs.map do |id, style_params|
      style_params[:id] = id
      Hairstyle.new(style_params.with_indifferent_access)
    end
  end
end

app/models/ordered_jsonb.rb
class OrderedJSONB
  class Type < ActiveRecord::Type::Value
    def type
      :jsonb
    end

    def cast(value)
      return {} if value.blank?
      hairstyle_hash_with_order(value.with_indifferent_access)
    end

    def deserialize(value)
      if String === value
        decoded = ::ActiveSupport::JSON.decode(value)
        hairstyle_hash_with_order(decoded)
      else
        super
      end
    end

    def serialize(value)
      case value
      when Hash
        value = value.with_indifferent_access
        unless value[:order]
          new_value = {}
          new_value[:order] = value.keys
          new_value[:attributes] = value
          value = new_value
        end

        ::ActiveSupport::JSON.encode(value)
      else
        super
      end
    end

    private

    def hairstyle_hash_with_order(decoded)
      if decoded["order"]
        decoded["order"].reduce({}) do |collector, id|
          collector.merge(id => decoded["attributes"][id])
        end
      else
        decoded
      end
    end
  end
end

app/models/style_position.rb
class StylePosition
  def initialize(hairstyle_list, style, direction)
    @hairstyle_list = hairstyle_list
    @style = style
    @direction = direction
  end

  def swap_position
    styles = @hairstyle_list.style_attributes
    return styles unless start_position && end_position

    styles_array = styles.to_a
    styles_array[start_position], styles_array[end_position] = styles_array[end_position], styles_array[start_position]
    styles_array.compact.to_h
  end

  private

  def start_position
    @start_position ||= @hairstyle_list.styles.index { |style| style.id == @style.id }
  end

  def end_position
    @end_position ||= case @direction
                      when "up"
                        start_position - 1
                      when "down"
                        start_position + 1
                      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hairstyle_lists_controller.rb
class HairstyleListsController < ApplicationController
  protect_from_forgery with: :exception

  def show
    @hairstyle_list = HairstyleList.find params[:id]
  end

  def update
    @hairstyle_list = HairstyleList.find params[:id]
    style = @hairstyle_list.find_style(params[:style_id])

    if @hairstyle_list
      @hairstyle_list.styles = StylePosition.new(@hairstyle_list, style, params[:direction]).swap_position
      @hairstyle_list.save

      redirect_to root_path
    else
      render body: nil, status: 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hairstyle_lists/show.html.erb
<h1>Hairstyles</h1>

<% @hairstyle_list.styles.each_with_index do |style, index| %>
  <div class="hairstyle">
    <div class="hairstyle-properties">
      Hair colour: <%= style.colour.titleize %><br />
      Part: <%= style.part.titleize %><br />
      Style: <%= style.style.titleize %><br />
      Length: <%= style.length.titleize %>
    </div>

    <div class="hairstyle-links">
      <% unless index == 0 %>
        <%= link_to "Move up", hairstyle_list_path(@hairstyle_list, style_id: style.id, direction: :up), method: :put %>
      <% end %>
      <% unless index == @hairstyle_list.styles.count - 1 %>
        <%= link_to "Move down", hairstyle_list_path(@hairstyle_list, style_id: style.id, direction: :down), method: :put %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsonbOrder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>